spring:
  application:
    name: e-commerce
  config:
    import: optional:file:.env
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jdbc:
    template:
      fetch-size: 200
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/
      file-extensions: .graphqls


  logging:
    level:
      com.example.e_commerce: DEBUG
