spring:
  application:
    name: e-commerce-test

  datasource:
    url: ${DB_URL}
    username: ${DB_USER_TEST}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jdbc:
    template:
      fetch-size: 200
