spring:
  application:
    name: e-commerce-test

  datasource:
    url: jdbc:postgresql://localhost:5432/e_commerce
    username: postgres
    password: Peggy@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
